/// CustomSubs - Privacy-First Subscription Tracker
///
/// A Flutter application for tracking subscriptions with complete privacy.
/// All data stays on-device with no cloud sync or network calls.
///
/// Key features:
/// - Offline-only operation
/// - Local Hive database
/// - Smart notifications with timezone support
/// - Multi-currency support with bundled exchange rates
/// - 40+ pre-populated subscription templates

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:timezone/data/latest_all.dart' as tz;
import 'package:custom_subs/app/app.dart';
import 'package:custom_subs/data/models/subscription.dart';
import 'package:custom_subs/data/models/subscription_cycle.dart';
import 'package:custom_subs/data/models/subscription_category.dart';
import 'package:custom_subs/data/models/reminder_config.dart';
import 'package:custom_subs/data/repositories/subscription_repository.dart';
import 'package:custom_subs/data/services/notification_service.dart';
import 'package:custom_subs/core/utils/currency_utils.dart';

/// Application entry point.
///
/// Performs critical initialization before starting the app:
/// 1. Initializes Hive database and registers type adapters
/// 2. Loads timezone data for notification scheduling
/// 3. Loads bundled currency exchange rates
/// 4. Initializes repositories and services
/// 5. Advances any overdue billing dates
/// 6. Re-schedules notifications for all active subscriptions
void main() async {
  // Required for async operations before runApp
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive local database (stores data in app documents directory)
  await Hive.initFlutter();

  // Register Hive type adapters for custom models
  // These are auto-generated by hive_generator via build_runner
  Hive.registerAdapter(SubscriptionAdapter());
  Hive.registerAdapter(SubscriptionCycleAdapter());
  Hive.registerAdapter(SubscriptionCategoryAdapter());
  Hive.registerAdapter(ReminderConfigAdapter());

  // Initialize timezone database for accurate notification scheduling
  // This loads timezone data for all regions worldwide
  tz.initializeTimeZones();

  // Load bundled currency exchange rates from assets/data/exchange_rates.json
  // This enables multi-currency support without network calls
  await CurrencyUtils.loadExchangeRates();

  // Create Riverpod container for dependency injection
  final container = ProviderContainer();

  // Initialize subscription repository (opens Hive box)
  // Using async provider pattern to handle initialization properly
  final repository = await container.read(subscriptionRepositoryProvider.future);

  // Initialize notification service (sets up platform-specific handlers)
  // The provider now auto-initializes the service
  final notificationService = await container.read(notificationServiceProvider.future);

  // Advance billing dates that are in the past to prevent outdated reminders
  // This ensures the app catches up if it hasn't been opened in a while
  await repository.advanceOverdueBillingDates();

  // Re-schedule all notifications for active subscriptions
  // This ensures notifications are up-to-date after app launch
  // (Needed because OS may clear scheduled notifications)
  final activeSubscriptions = repository.getAllActive();
  for (final subscription in activeSubscriptions) {
    await notificationService.scheduleNotificationsForSubscription(subscription);
  }

  // Start the Flutter application
  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const CustomSubsApp(),
    ),
  );
}
